import Image from 'next/image';
import Journey from '@/components/Journey';
const projects = [
  { title: 'Eric’s Auto Care', label: 'AI AGENT · SMALL BUSINESS', text: 'An assistant built around the everyday questions and booking needs of an auto repair shop.', link: 'https://small-business-agent.vercel.app', image: '/projects/auto-care.jpg', color: 'pink' },
  { title: 'Live Suggestion Agent', label: 'REALTIME AI · CONVERSATION', text: 'Context-aware suggestions during live conversations, designed to help at the moment they matter.', link: 'https://twinmind-live-suggestion-liart.vercel.app', image: '/projects/live-agent.jpg', color: 'green' },
  { title: 'Email Intelligence', label: 'GRAPHRAG · WORKFLOWS', text: 'Turning scattered email threads into a clearer picture of tasks, relationships, and what needs attention.', link: 'https://huggingface.co/spaces/rsm-wew068/automated-task-manager', image: '/projects/email-intelligence.jpg', color: 'purple' },
];
export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><a className="brand" href="#">rachel<span>wang</span><i>✳</i></a><nav aria-label="Main navigation"><a href="#story">My story</a><a href="#work">Selected work</a><a href="mailto:ygweihsien910622@gmail.com" className="nav-contact">Let’s talk <span>↗</span></a></nav></header>
    <main id="main">
      <section className="hero">
        <div className="hero-copy"><p className="eyebrow"><span className="small-star">✳</span> A little curiosity goes a long way</p><h1>People first.<br/>Then <em>possibility.</em></h1><p className="hero-intro">Hi, I’m Rachel. I bring design, psychology, marketing, and analytics together to build AI products people love using.</p><a href="#story" className="primary-link">Here’s how I got here <span>↓</span></a><div className="hero-caption"><span>AI product builder</span><i>·</i><span>MS Business Analytics, UC San Diego</span></div></div>
        <div className="portrait-composition"><div className="portrait-frame"><Image src="/rachel-coast.jpg" alt="Rachel Wang" fill priority sizes="(max-width: 760px) 80vw, 420px" className="portrait"/><div className="portrait-label">Rachel Wang <span>Always asking why.</span></div></div><span className="orbit-label label-design">an eye for design <i>◐</i></span><span className="orbit-label label-people"><i>♡</i> a mind for people</span><span className="orbit-label label-data">a habit of asking why <i>↗</i></span><span className="portrait-star" aria-hidden="true">✳</span><svg className="scribble" viewBox="0 0 160 90" aria-hidden="true"><path d="M5 65 Q70 5 100 40 T145 30 M130 28 L148 28 L144 46"/></svg></div>
      </section>
      <section id="story" className="section story-section"><div className="section-heading"><p className="eyebrow">01 / The path that shaped me</p><h2>A winding path.<br/><em>A clear purpose.</em></h2><p>I’ve always been curious about what makes people care—and what makes a product worth coming back to. Each chapter gave me a different way to answer that question.</p></div><Journey/></section>
      <section className="approach section"><div><p className="eyebrow">02 / How I build</p><h2>The journey comes<br/>before the <em>pipeline.</em></h2><p className="approach-intro">I start with what someone wants to accomplish, where they get stuck, and what would make the next step feel effortless.</p><p>Then I work with AI collaborators to design the technical pipeline around that journey. Every feature has to earn its place in the user’s experience.</p></div><ol className="workflow"><li><span>01</span><div><h3>Understand the person</h3><p>Find the real need behind the request.</p></div><i>◎</i></li><li><span>02</span><div><h3>Map the whole journey</h3><p>Outline the experience, from first click to outcome.</p></div><i>↝</i></li><li><span>03</span><div><h3>Build with AI collaborators</h3><p>Design the system around the workflow.</p></div><i>✳</i></li><li><span>04</span><div><h3>Test. Learn. Make it better.</h3><p>Check whether it delivers for the people using it.</p></div><i>↗</i></li></ol></section>
      <section id="work" className="section work-section"><div className="work-heading"><div><p className="eyebrow">03 / Ideas made real</p><h2>Curiosity, <em>in practice.</em></h2></div><a href="https://github.com/rsm-wew068" target="_blank" rel="noreferrer">More on GitHub ↗</a></div><div className="project-grid">{projects.map(project => <a className={`project-card ${project.color}`} href={project.link} key={project.title} target="_blank" rel="noreferrer"><div className="project-art"><Image src={project.image} alt={`${project.title} interface screenshot`} fill sizes="(max-width: 760px) 90vw, 380px" className="project-screenshot"/><i aria-hidden="true">↗</i></div><p className="eyebrow">{project.label}</p><h3>{project.title}</h3><p>{project.text}</p><span className="project-cta">Explore the live project ↗</span></a>)}</div></section>
      <section className="contact section"><p className="eyebrow">Something worth building?</p><h2>Let’s make people<br/><em>love using it.</em></h2><a href="https://www.linkedin.com/in/wei-hsien-wang-b21922230/" target="_blank" rel="noreferrer" className="primary-link">Start a conversation <span>↗</span></a><div className="contact-photo"><Image src="/golden-gate.jpg" alt="Golden Gate Bridge over San Francisco Bay" fill sizes="(max-width: 760px) 80vw, 330px"/></div></section>
    </main><footer><a className="brand" href="#">rachel<span>wang</span><i>✳</i></a><p>Made with curiosity. Built around people.</p><a href="https://github.com/rsm-wew068" target="_blank" rel="noreferrer">GitHub ↗</a></footer>
  </>;
}
